### ISSUE TITLE
Not reporting PHP / MySQL version could cause future update problems

### ISSUE THREAD

**Issue by mattradford** [mattradford/update-privacy#1]
If WordPress drops support for olders versions of PHP and MySQL, updates could be offered based on whether the site is reporting a supported PHP/MySQL version. The plugin currently unsets sending PHP and MySQL.

**Comment by schliflo** [comment]
This should be handled locally after checking for & downloading the update. Idk about the current behaviour on this: does WP update to an "unsupported" state or does the updater do some pre-update checks to prevent this?

**Comment by mattradford** [comment]
I don't know, and haven't looked into it. If WP does set a higher minimum PHP version, it'll be well publicised, so I'll look into it then. But from my discussion with a member of the core team, removing  PHP and MySQL from the version check will not affect the upgrade process, as that will separately check that the server is a supported environment for the upgrade.

**Comment by schliflo** [comment]
So basically it's not an issue because the updater takes care of it locally.
